### ISSUE TITLE
Quotes removed from stored value when read

### ISSUE THREAD

**Issue by awchristie1** [neosmart/SecureStore#23]
Value created with CLI executable imports into C# without quotes (") in the string or bytes returned.  The rest of the content seems fine, but the missing quotes are making JSON unhappy.

**Comment by mqudsi** [comment]
This isn’t a bug, it’s because of how quoting works in the terminal/shell. 

You need to escape the quotes, but it’s easier to use direct entry method. Instead of `ssclient … set foo bar` do `ssclient set foo` then press enter. It’ll give you a prompt to enter it in the cli directly without the shell in the way.
